sequenceDiagram
  participant Cloud Scheduler
  participant API
  participant Database
  participant OSCN
  participant Cloud Storage
  Cloud Scheduler->>API: /hydrate
  API->>OSCN: Scrape
  OSCN-->>API: Documents
  API->>Database: Documents
  API->>Cloud Storage: Documents
